apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      imagePullPolicy: Never   # Use the locally built image
      command: ["sleep"]
      args: ["10"]

  