apiVersion: v1
kind: Pod 
metadata: 
  name: simple-webapp-colors
  labels:
    name: simple-webapp-colors
spec:
  containers:
  - name: simple-webapp-colors
    image: simple-webapp-colors
    ports: 
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name : app-config
