apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-service
spec:
  selector:
    app: simple-webapp-colors
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort 